// scripts/build-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'node_modules/@material-symbols/svg-200/outlined')

// Deduped Material Symbols names in use (see plan's mapping table).
export const MANIFEST = [
  'add', 'arrow_forward', 'attach_money', 'check', 'check_circle', 'chevron_left',
  'chevron_right', 'close', 'content_copy', 'dangerous', 'dashboard', 'delete',
  'description', 'dock_to_left', 'edit', 'folder_open', 'format_align_center',
  'format_align_left', 'format_align_right', 'format_bold', 'format_italic',
  'format_underlined', 'group', 'help', 'info', 'keyboard_arrow_down',
  'keyboard_arrow_up', 'keyboard_command_key', 'language', 'menu_book', 'more_horiz',
  'notifications', 'palette', 'progress_activity', 'remove', 'search', 'settings',
  'star', 'warning',
]

function parseSvg(name) {
  const svg = readFileSync(join(SRC, `${name}.svg`), 'utf8')
  const vb = svg.match(/viewBox="([^"]+)"/)
  if (!vb) throw new Error(`${name}: no viewBox`)
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1])
  if (!paths.length) throw new Error(`${name}: no <path> found`)
  return { viewBox: vb[1], paths }
}

export function build() {
  const entries = MANIFEST.slice().sort().map((n) => [n, parseSvg(n)])
  const body = entries
    .map(([n, v]) => `  ${JSON.stringify(n)}: ${JSON.stringify(v)},`)
    .join('\n')
  const mjs = `// GENERATED by scripts/build-icons.mjs — do not edit. Source: @material-symbols/svg-200 (outlined).\nexport const icons = {\n${body}\n}\n`

  const nameUnion = entries.map(([n]) => `'${n}'`).join(' | ')
  const dts = `// GENERATED by scripts/build-icons.mjs — do not edit.\nexport type IconName = ${nameUnion}\nexport declare const icons: Record<IconName, { viewBox: string; paths: string[] }>\n`

  return { mjs, dts }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { mjs, dts } = build()
  writeFileSync(join(root, 'src/components/ui/icons.generated.mjs'), mjs)
  writeFileSync(join(root, 'src/components/ui/icons.generated.d.mts'), dts)
}
