// scripts/build-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { MANIFEST } from './icons.manifest.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'node_modules/@material-symbols/svg-200/outlined')

// MANIFEST (top ~1000 Material Symbols Outlined by Google popularity + in-use icons)
// lives in scripts/icons.manifest.mjs — regenerate it via scripts/build-manifest.mjs.
export { MANIFEST }

function parseSvg(name) {
  const svg = readFileSync(join(SRC, `${name}.svg`), 'utf8')
  const vb = svg.match(/viewBox="([^"]+)"/)
  if (!vb) throw new Error(`${name}: no viewBox`)
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1])
  if (!paths.length) throw new Error(`${name}: no <path> found`)
  return { viewBox: vb[1], paths }
}

export function build() {
  const entries = MANIFEST.slice().sort().map((n) => [n, parseSvg(n)])
  const body = entries
    .map(([n, v]) => `  ${JSON.stringify(n)}: ${JSON.stringify(v)},`)
    .join('\n')
  const mjs = `// GENERATED by scripts/build-icons.mjs — do not edit. Source: @material-symbols/svg-200 (outlined).\nexport const icons = {\n${body}\n}\n`

  const nameUnion = entries.map(([n]) => `'${n}'`).join(' | ')
  const dts = `// GENERATED by scripts/build-icons.mjs — do not edit.\nexport type IconName = ${nameUnion}\nexport declare const icons: Record<IconName, { viewBox: string; paths: string[] }>\n`

  return { mjs, dts }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { mjs, dts } = build()
  writeFileSync(join(root, 'src/components/ui/icons.generated.mjs'), mjs)
  writeFileSync(join(root, 'src/components/ui/icons.generated.d.mts'), dts)
}
