'use client'

import * as React from 'react'
import { cn } from '@/lib/utils'
import { icons } from './icons.core.mjs'
import type { IconName } from './icons.generated'

// Icon delivery: sync core → per-icon lazy → grouped-tail fallback.
// - Core icons (usage-derived ∪ curated common) live in icons.core.mjs and are
//   imported synchronously → instant render, no flash / layout shift.
// - Every other name tries a per-icon module (src/components/ui/icons/<name>.mjs,
//   generated by `npm run build:icons`, gitignored). Dynamic-imported on mount via
//   `import(\`./icons/${name}.mjs\`)` — the bundler auto-code-splits each chunk so
//   the initial graph only carries <Icon> + the core map.
// - If the per-icon import REJECTS (name not in the top-2000 set), falls back to
//   `import('./icons.tail.mjs')`, a single grouped map of the entire remaining
//   outlined library, and looks the name up there.
// A module-level cache means each lazy or tail icon loads at most once per session.

type IconData = { viewBox: string; paths: string[] }

const coreIcons = icons as Record<string, IconData>
const lazyCache = new Map<string, IconData>()

function Icon({
  name,
  size = '1em',
  className,
  'aria-label': ariaLabel,
  ...props
}: React.SVGProps<SVGSVGElement> & { name: IconName; size?: number | string }) {
  const core = coreIcons[name]

  const [lazy, setLazy] = React.useState<{ name: string; data: IconData } | null>(
    () => {
      const cached = lazyCache.get(name)
      return cached ? { name, data: cached } : null
    }
  )
  // Keyed by name so a new valid `name` clears any stale error from a prior bad name.
  const [error, setError] = React.useState<{ name: string; err: Error } | null>(null)

  React.useEffect(() => {
    if (core) return
    const cached = lazyCache.get(name)
    if (cached) {
      // Cache hit on a changed name: sync setState avoids a one-frame empty
      // icon; the module-level cache is external to React by design.
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setLazy({ name, data: cached })
      return
    }
    let active = true
    import(`./icons/${name}.mjs`)
      .then((mod) => {
        const data = mod.default as IconData
        lazyCache.set(name, data)
        if (active) setLazy({ name, data })
      })
      .catch(async (perIconErr: unknown) => {
        // Per-icon module not found → fall back to the grouped tail map.
        try {
          const tailMod = await import('./icons.tail.mjs')
          const tailMap = (tailMod as { icons: Record<string, IconData> }).icons
          const data = tailMap[name]
          if (data) {
            lazyCache.set(name, data)
            if (active) setLazy({ name, data })
          } else {
            // Not in core, per-icon, or tail → genuinely unknown.
            if (active)
              setError({
                name,
                err: new Error(`Unknown icon: ${String(name)}`, { cause: perIconErr }),
              })
          }
        } catch (tailErr: unknown) {
          if (active)
            setError({
              name,
              err: new Error(`Unknown icon: ${String(name)}`, { cause: perIconErr }),
            })
        }
      })
    return () => {
      active = false
    }
  }, [name, core])

  // Surface unknown-icon failures loudly in dev; render nothing in prod.
  // Only throw if the error belongs to the CURRENT name (stale errors from a prior
  // name prop are ignored — they will be cleared by the running effect above).
  if (error && error.name === name && process.env.NODE_ENV !== 'production') throw error.err

  const data =
    core ?? (lazy && lazy.name === name ? lazy.data : lazyCache.get(name))

  // Not yet resolved → same-size reserved placeholder (no layout shift).
  const viewBox = data?.viewBox ?? '0 0 24 24'

  return (
    <svg
      data-slot="icon"
      viewBox={viewBox}
      width={size}
      height={size}
      fill="currentColor"
      role={ariaLabel ? 'img' : undefined}
      aria-label={ariaLabel}
      aria-hidden={ariaLabel ? undefined : true}
      className={cn('inline-block shrink-0', className)}
      {...props}
    >
      {data?.paths.map((d, i) => <path key={i} d={d} />)}
    </svg>
  )
}

export { Icon, type IconName }
